### ISSUE TITLE
[Question] Auth implementation may hold security flaws

### ISSUE THREAD

**Issue by DatMayo** [masonschafercodes/next-prisma-auth-template#1]
Hey,

I'm rather new to nuxt, so please bare with me. 
If I got your code right, you do this on every protected route:
```ts
const session = await getSession({ req });
if (!session) return res.status(401).end();
```
I see that a lot on next.js projects and I think, wouldn't it be easier to have a middleware with a list of whitelisted (non authed) routes? So the middleware could take care of all other routes and check the credentials on one central place instead of every single route?

**Comment by masonschafercodes** [comment]
I actually like that idea, I am about to push up a a change that uses middleware instead of checking the session every time.
